/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdminDashboard {
    }
    interface AdminDashboardShipmentlist {
    }
    interface AdminLoginPage {
    }
    interface AdminSignupPage {
    }
    interface CreateShipmentPage {
    }
    interface HomePage {
    }
    interface HomeProfilePage {
    }
    interface LoginPage {
    }
    interface PricingPage {
    }
    interface RootPage {
    }
    interface ShipmentDetailPage {
    }
    interface SignupPage {
    }
    interface TrackingPage {
    }
    interface ViewShipmentPage {
    }
}
declare global {
    interface HTMLAdminDashboardElement extends Components.AdminDashboard, HTMLStencilElement {
    }
    var HTMLAdminDashboardElement: {
        prototype: HTMLAdminDashboardElement;
        new (): HTMLAdminDashboardElement;
    };
    interface HTMLAdminDashboardShipmentlistElement extends Components.AdminDashboardShipmentlist, HTMLStencilElement {
    }
    var HTMLAdminDashboardShipmentlistElement: {
        prototype: HTMLAdminDashboardShipmentlistElement;
        new (): HTMLAdminDashboardShipmentlistElement;
    };
    interface HTMLAdminLoginPageElement extends Components.AdminLoginPage, HTMLStencilElement {
    }
    var HTMLAdminLoginPageElement: {
        prototype: HTMLAdminLoginPageElement;
        new (): HTMLAdminLoginPageElement;
    };
    interface HTMLAdminSignupPageElement extends Components.AdminSignupPage, HTMLStencilElement {
    }
    var HTMLAdminSignupPageElement: {
        prototype: HTMLAdminSignupPageElement;
        new (): HTMLAdminSignupPageElement;
    };
    interface HTMLCreateShipmentPageElement extends Components.CreateShipmentPage, HTMLStencilElement {
    }
    var HTMLCreateShipmentPageElement: {
        prototype: HTMLCreateShipmentPageElement;
        new (): HTMLCreateShipmentPageElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLHomeProfilePageElement extends Components.HomeProfilePage, HTMLStencilElement {
    }
    var HTMLHomeProfilePageElement: {
        prototype: HTMLHomeProfilePageElement;
        new (): HTMLHomeProfilePageElement;
    };
    interface HTMLLoginPageElement extends Components.LoginPage, HTMLStencilElement {
    }
    var HTMLLoginPageElement: {
        prototype: HTMLLoginPageElement;
        new (): HTMLLoginPageElement;
    };
    interface HTMLPricingPageElement extends Components.PricingPage, HTMLStencilElement {
    }
    var HTMLPricingPageElement: {
        prototype: HTMLPricingPageElement;
        new (): HTMLPricingPageElement;
    };
    interface HTMLRootPageElement extends Components.RootPage, HTMLStencilElement {
    }
    var HTMLRootPageElement: {
        prototype: HTMLRootPageElement;
        new (): HTMLRootPageElement;
    };
    interface HTMLShipmentDetailPageElement extends Components.ShipmentDetailPage, HTMLStencilElement {
    }
    var HTMLShipmentDetailPageElement: {
        prototype: HTMLShipmentDetailPageElement;
        new (): HTMLShipmentDetailPageElement;
    };
    interface HTMLSignupPageElement extends Components.SignupPage, HTMLStencilElement {
    }
    var HTMLSignupPageElement: {
        prototype: HTMLSignupPageElement;
        new (): HTMLSignupPageElement;
    };
    interface HTMLTrackingPageElement extends Components.TrackingPage, HTMLStencilElement {
    }
    var HTMLTrackingPageElement: {
        prototype: HTMLTrackingPageElement;
        new (): HTMLTrackingPageElement;
    };
    interface HTMLViewShipmentPageElement extends Components.ViewShipmentPage, HTMLStencilElement {
    }
    var HTMLViewShipmentPageElement: {
        prototype: HTMLViewShipmentPageElement;
        new (): HTMLViewShipmentPageElement;
    };
    interface HTMLElementTagNameMap {
        "admin-dashboard": HTMLAdminDashboardElement;
        "admin-dashboard-shipmentlist": HTMLAdminDashboardShipmentlistElement;
        "admin-login-page": HTMLAdminLoginPageElement;
        "admin-signup-page": HTMLAdminSignupPageElement;
        "create-shipment-page": HTMLCreateShipmentPageElement;
        "home-page": HTMLHomePageElement;
        "home-profile-page": HTMLHomeProfilePageElement;
        "login-page": HTMLLoginPageElement;
        "pricing-page": HTMLPricingPageElement;
        "root-page": HTMLRootPageElement;
        "shipment-detail-page": HTMLShipmentDetailPageElement;
        "signup-page": HTMLSignupPageElement;
        "tracking-page": HTMLTrackingPageElement;
        "view-shipment-page": HTMLViewShipmentPageElement;
    }
}
declare namespace LocalJSX {
    interface AdminDashboard {
    }
    interface AdminDashboardShipmentlist {
    }
    interface AdminLoginPage {
    }
    interface AdminSignupPage {
    }
    interface CreateShipmentPage {
    }
    interface HomePage {
    }
    interface HomeProfilePage {
    }
    interface LoginPage {
    }
    interface PricingPage {
    }
    interface RootPage {
    }
    interface ShipmentDetailPage {
    }
    interface SignupPage {
    }
    interface TrackingPage {
    }
    interface ViewShipmentPage {
    }
    interface IntrinsicElements {
        "admin-dashboard": AdminDashboard;
        "admin-dashboard-shipmentlist": AdminDashboardShipmentlist;
        "admin-login-page": AdminLoginPage;
        "admin-signup-page": AdminSignupPage;
        "create-shipment-page": CreateShipmentPage;
        "home-page": HomePage;
        "home-profile-page": HomeProfilePage;
        "login-page": LoginPage;
        "pricing-page": PricingPage;
        "root-page": RootPage;
        "shipment-detail-page": ShipmentDetailPage;
        "signup-page": SignupPage;
        "tracking-page": TrackingPage;
        "view-shipment-page": ViewShipmentPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admin-dashboard": LocalJSX.AdminDashboard & JSXBase.HTMLAttributes<HTMLAdminDashboardElement>;
            "admin-dashboard-shipmentlist": LocalJSX.AdminDashboardShipmentlist & JSXBase.HTMLAttributes<HTMLAdminDashboardShipmentlistElement>;
            "admin-login-page": LocalJSX.AdminLoginPage & JSXBase.HTMLAttributes<HTMLAdminLoginPageElement>;
            "admin-signup-page": LocalJSX.AdminSignupPage & JSXBase.HTMLAttributes<HTMLAdminSignupPageElement>;
            "create-shipment-page": LocalJSX.CreateShipmentPage & JSXBase.HTMLAttributes<HTMLCreateShipmentPageElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "home-profile-page": LocalJSX.HomeProfilePage & JSXBase.HTMLAttributes<HTMLHomeProfilePageElement>;
            "login-page": LocalJSX.LoginPage & JSXBase.HTMLAttributes<HTMLLoginPageElement>;
            "pricing-page": LocalJSX.PricingPage & JSXBase.HTMLAttributes<HTMLPricingPageElement>;
            "root-page": LocalJSX.RootPage & JSXBase.HTMLAttributes<HTMLRootPageElement>;
            "shipment-detail-page": LocalJSX.ShipmentDetailPage & JSXBase.HTMLAttributes<HTMLShipmentDetailPageElement>;
            "signup-page": LocalJSX.SignupPage & JSXBase.HTMLAttributes<HTMLSignupPageElement>;
            "tracking-page": LocalJSX.TrackingPage & JSXBase.HTMLAttributes<HTMLTrackingPageElement>;
            "view-shipment-page": LocalJSX.ViewShipmentPage & JSXBase.HTMLAttributes<HTMLViewShipmentPageElement>;
        }
    }
}
